name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            workwithprashant/docker-selenium3:${{ env.VERSION }}
            workwithprashant/docker-selenium3:latest
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag docker-selenium3:latest
#       - name: Tag Docker image
#         run: docker tag docker-selenium3:latest workwithprashant/docker-selenium3:latest
      - name: Push Docker images
        run: docker push workwithprashant/docker-selenium3:${{ env.VERSION }}
      - name: Push Docker images
        run: docker push workwithprashant/docker-selenium3:latest
